### ISSUE TITLE
Unable to retrieve last oplog. Maybe you are not running your mongodb in a replica set

### ISSUE THREAD

**Issue by Brice187** [Maltcommunity/mongo-postgresql-streamer#8]
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.4.RELEASE)

2020-12-03 17:01:26,060 INFO  [main] StreamerApplication: Starting StreamerApplication v0.0.1-SNAPSHOT on mongo-postgresql-streamer-cronjob with PID 8 (/opt/jars/mongo-postgresql-streamer-0.0.1-SNAPSHOT.jar started by root in /)
2020-12-03 17:01:26,064 INFO  [main] StreamerApplication: No active profile set, falling back to default profiles: default
2020-12-03 17:01:30,647 INFO  [main] StreamerApplication: Started StreamerApplication in 4.984 seconds (JVM running for 5.573)
2020-12-03 17:01:30,690 INFO  [main] StreamerApplication: No checkpoint found, we will perform a initial load
2020-12-03 17:01:30,697 ERROR [main] SpringApplication: Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:794)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at com.malt.mongopostgresqlstreamer.StreamerApplication.main(StreamerApplication.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: Unable to retrieve last oplog. Maybe you are not running your mongodb in a replica set
	at com.malt.mongopostgresqlstreamer.CheckpointManager.getLastOplog(CheckpointManager.java:80)
	at com.malt.mongopostgresqlstreamer.StreamerApplication.run(StreamerApplication.java:47)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	... 13 common frames omitted
```
Can `mongo-postgresql-streamer` be run on a single instance?

**Comment by seuf** [comment]
Hi, no mongo streamer concept is to follow the oplog (of a replicaet) to send it to postgresql.
So you must have a replicaset initilized with `rs.initiate()`
